[build]
  # Specify the publish directory
  publish = "public/ai"
  
  # Optional: if you have a build command, specify it here
  # command = "npm run build"

[build.environment]
  # Set any environment variables if needed
  NODE_VERSION = "18"

# Optional: Set up redirects if needed
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Optional: Set custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
